---
# This is the most common network topology for OpenStack Testing deployments
#
networks:
    data:
        name: '{{ run.uuid }}-data'
    external:
        name: '{{ run.uuid }}-external'
    management:
        name: '{{ run.uuid }}-management'

subnets:
    data:
        name: "{{ !lookup provisioner.network.networks.data.name }}"
        network_name: "{{ !lookup provisioner.network.networks.data.name }}"
        allocation_pool_start: 172.16.1.10
        allocation_pool_start: 172.16.1.100
        cidr: 172.16.1.0/24
    external:
        name: "{{ !lookup provisioner.network.networks.external.name }}"
        network_name: "{{ !lookup provisioner.network.networks.external.name }}"
        allocation_pool_start: 172.31.0.10
        allocation_pool_start: 172.31.0.100
        cidr: 172.31.0.0/23
    management:
        name: "{{ !lookup provisioner.network.networks.management.name }}"
        network_name: "{{ !lookup provisioner.network.networks.management.name }}"
        allocation_pool_start: 192.168.1.10
        allocation_pool_start: 192.168.1.100
        cidr: 192.168.1.0/24

rotuers:
    router:
        name: '{{ run.uuid }}-router'
        attach_subnets:
            - "{{ !lookup provisioner.network.subnets.external.name }}"
            - "{{ !lookup provisioner.network.subnets.management.name }}"
        # network: "{{ !lookup private.networks.public }}"
