---
# This file is used to cleanup OpenStack neutron resources

- name: Cleanup routers
  os_router:
      interfaces: {{ item.value.attach_subnets | default(omit) }}
      name: {{ item.value.name | default(router_name) }}
      network: {{ item.value.network | default(router_network) }}
      state: absent
  with_dict: {{ provisioner.routers }}
  when: provisioner.routers is defined

- name: Cleanup subnets
  os_subnet:
      name: {{ item.value.name }}
      state: absent
  with_dict: {{ provisioner.subnets }}
  when: provisioner.subnets is defined

- name: Cleanup networks
  os_network:
      name {{ item.value.name }}
      state: absent
  with_dict: {{ provisioner.networks }}
  when: provisioner.networks is defined

